module DiamondScheduler
  VERSION = "0.1.1"
  VERSION_MAJOR = 0
  VERSION_MINOR = 1
  VERSION_PATCH = 1

  APP_VERSION = "7.0.1"
  APP_VERSION_MAJOR = 7
  APP_VERSION_MINOR = 0
  APP_VERSION_PATCH = 1

  APP_BUILD = "0.0.732"
  APP_BUILD_MAJOR = 0
  APP_BUILD_MINOR = 0
  APP_BUILD_PATCH = 732
end
