ruby '2.2.0'
source 'https://rubygems.org'

gem 'activesupport'
gem 'async_sinatra'
gem 'guard'
gem 'guard-rspec'
gem 'nestful'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'oauth2'
gem 'dotenv'
gem 'nokogiri'
gem 'launchy'